### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by BalajiAI** [gaopengcuhk/Stable-Pix2Seq#1]
Can you share the pretrained weights for evaluation?

**Comment by gaopengcuhk** [comment]
If you want to play with Pix2Seq with pretrained model, please go to https://github.com/gaopengcuhk/Unofficial-Pix2Seq. The checkpoint for Stable-Pix2Seq need 10 days to be trained on 8 V100 GPU.

**Comment by BalajiAI** [comment]
Oh ok sir.
