### ISSUE TITLE
How to using for panoptic segmentation

### ISSUE THREAD

**Issue by byrsongyuxin** [gaopengcuhk/Stable-Pix2Seq#2]
can you share the command line when training panoptic seg.  I using the command: 
python -m torch.distributed.launch --nproc_per_node=1 --use_env main.py --coco_path ... --coco_panoptic_path ... --masks
but, there are some error.

**Comment by gaopengcuhk** [comment]
Panoptic is a typo. We do not support panoptic segmentation currently. The main propose of this project is to replicate Pix2Seq.
