### ISSUE TITLE
Performance compared to paper

### ISSUE THREAD

**Issue by sauradip** [gaopengcuhk/Stable-Pix2Seq#3]
Hi ,

Thank you for making this implementation so fast ! How is the difference of this implementation with the reported numbers  in the paper ?

**Comment by gaopengcuhk** [comment]
Please wait a moment

**Comment by gaopengcuhk** [comment]
Please wait few days. The data loader in stable-pix2seq has been updated. I am retraining stable-pix2seq with 1333 image resolution while old stable-pix2seq uses 512 image resolution by default.

**Comment by gaopengcuhk** [comment]
By adding new augmentation, stable-pix2seq could achieve 34mAP at 218 epoches

**Comment by gaopengcuhk** [comment]
256 epoch 36mAP. Beam search will addition improve 1-2 mAP. The estimated mAP is 37-38mAP at 256 epoch.

**Comment by gaopengcuhk** [comment]
We released the pretrained model at https://github.com/gaopengcuhk/Pretrained-Pix2Seq.
