### ISSUE TITLE
Performance Difference Compared With Original Paper？

### ISSUE THREAD

**Issue by xmu-xiaoma666** [gaopengcuhk/Stable-Pix2Seq#5]
Thank you for your implementation!!!
Can you share Performance Difference Compared With Original Paper and checkpoint?

**Comment by gaopengcuhk** [comment]
I am still running experiments.

**Comment by Yuliang-Liu** [comment]
Is there any update of the performance?

**Comment by gaopengcuhk** [comment]
By adding new augmentation, stable-pix2seq could achieve 34mAP at 218 epoches

**Comment by xmu-xiaoma666** [comment]
> By adding new augmentation, stable-pix2seq could achieve 34mAP at 218 epoches

The paper reports 45.0mAP？
![image](https://user-images.githubusercontent.com/33897496/139184628-2e671486-2e34-45f6-8e96-3f641ba6f9ba.png)

**Comment by gaopengcuhk** [comment]
The reported performance is 43.0 mAP. The paper lack details about the implementation. We are trying our best to replicate the results reported in the paper.  As the training process is slow, it may take several months to replicate the results. We will update the results on this GitHub once we have progress,

**Comment by gaopengcuhk** [comment]
256 epoch 36mAP. Beam search will addition improve 1-2 mAP. The estimated mAP is 37-38mAP at 256 epoch.

**Comment by seanzhuh** [comment]
Will you release the beam search code?

**Comment by gaopengcuhk** [comment]
All code including beam search and data augmentation will be released.

**Comment by baiyongrui** [comment]
Does Pix2Seq converge slower than DETR?

**Comment by gaopengcuhk** [comment]
Due to different learning schedules, it's hard to compare the convergence speed between DETR and Pix2Seq.

**Comment by gaopengcuhk** [comment]
We released the pretrained model at https://github.com/gaopengcuhk/Pretrained-Pix2Seq.
