### ISSUE TITLE
How to do visualization analysis?

### ISSUE THREAD

**Issue by zhangjx123** [gaopengcuhk/Stable-Pix2Seq#7]
How to do visualization analysis? Could you share some scripts? 
Thanks

**Comment by gaopengcuhk** [comment]
Please refer to https://github.com/gaopengcuhk/Unofficial-Pix2Seq for visualization of the bounding box.

**Comment by zhangjx123** [comment]
> Please refer to https://github.com/gaopengcuhk/Unofficial-Pix2Seq for visualization of the bounding box.

Thank you very much
