### ISSUE TITLE
About the details of the code

### ISSUE THREAD

**Issue by hcy226** [gaopengcuhk/Stable-Pix2Seq#8]
What's the usage of weight[1998]=0.01 and weight[2000]=0.01？
I want to extend the code to the Panoptic Segmentation and wonder how to modify it

**Comment by gaopengcuhk** [comment]
1998 and 2000 is EOS and N/A token defined in Pix2Seq. To better balance the loss, we set EOS and N/A tokens with a smaller weight. This is not mentioned in Pix2Seq. I am not sure this is the best practice or not.

**Comment by hughwcq** [comment]
And i find it`s so slow when evaluating, because eos token is set false?
